apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-ds
spec:
  template:
    metadata:
      labels:
        env: demo
      name: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
  selector:
   matchLabels:
    # Every pod with this label will be managed by the DaemonSet
    env: demo