apiVersion: v1
kind: Pod
metadata:
  name: redis-pod2
spec:
  containers:
    - name: redis-container
      image: redis:latest
      volumeMounts:
        - name: redis-storage
          mountPath: /data
  volumes:
    - name: redis-storage
      persistentVolumeClaim:
        claimName: redis-pvc