apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  # The path on the host machine where data will be stored
  # Just for debug and local development
  hostPath:
   path: /home/user/redis-data